base:
  random_state: 20

make_dataset:
  # Default feature names
  # - title: title
  # - description: description
  # Default target name: category
  datasets:
    [
      {
        dir: "data/raw/YouTube Titles and description using youtube api.csv",
        feature_names: { title: "Title", description: "Description" },
        target: "Category",
      },
      {
        dir: "data/raw/Youtube Video Dataset.csv",
        feature_names: { title: "Title", description: "Description" },
        target: "Category",
      },
      { dir: "data/raw/youtube.csv" },
    ]

clean_dataset:
  english_threshold_confidence: 0.95
  min_token_length: 3
  min_tokens_count: 5

build_features:
  test_size: 0.2
  min_df: 0.05
